
      // 
      // Javascript generated by HTML2 Toolkit plugin
      // 
      var tree;
      
      function treeInit() {
      tree = new YAHOO.widget.TreeView("treeDiv1");
      var root = tree.getRoot();

      
var objd64e75 = {
  label: " DITA For Small Teams",
  href: "topics/dita-for-small-teams.html", 
  target:"contentwin"
};
var d64e75 = new YAHOO.widget.TextNode(objd64e75, root, false);

var objd64e100 = {
  label: " DITA for Small Teams Tools",
  href: "topics/dfst-tools.html", 
  target:"contentwin"
};
var d64e100 = new YAHOO.widget.TextNode(objd64e100, d64e75, false);

var objd64e125 = {
  label: " git: Distributed and Shared Access to Content",
  href: "topics/tools-git.html", 
  target:"contentwin"
};
var d64e125 = new YAHOO.widget.TextNode(objd64e125, d64e100, false);

var objd64e150 = {
  label: " eXist-db: Enabling Search and Link Management",
  href: "topics/tools-exist-db.html", 
  target:"contentwin"
};
var d64e150 = new YAHOO.widget.TextNode(objd64e150, d64e100, false);

      
      tree.draw(); 
      } 
      
      YAHOO.util.Event.addListener(window, "load", treeInit);       
    